/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DellStore.ui.manager;

import DellStore.dao.impl.cardDAOImpl;
import DellStore.dao.impl.chitietsanphamDAO;
import DellStore.dao.impl.cpuDAOImpl;
import DellStore.dao.impl.hangDAOImpl;
import DellStore.dao.impl.ocungDAOImpl;
import DellStore.dao.impl.ramDAOImpl;
import DellStore.entity.card;
import DellStore.entity.chitietsanpham;
import DellStore.entity.cpu;
import DellStore.entity.hang;
import DellStore.entity.ocung;
import DellStore.entity.ram;
import DellStore.utils.XJdbc;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author docon
 */
public class SanPhamJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SanPhamJPanel
     */
    public SanPhamJPanel() {
        initComponents();
         DefaultTableModel model = new DefaultTableModel();
   model.setColumnIdentifiers(new Object[]{
    "STT", "Tên sản phẩm", "ram", "Cpu", "Ỏ Cứng", "card", "hãng", "Serial", "Giá bán", "Trạng thái"
});
    tbl_bangDSSanPham.setModel(model);
        fillcomboboxram();
        fillComboBoxCPU();
        fillComboBoxHang();
        fillComboBoxOCung();
        fillComboBoxCard();
        fillTableChiTietSanPham();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txt_tensanpham = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_timkiemsanpham = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_timkiemsanpham = new javax.swing.JButton();
        btn_themsanpham = new javax.swing.JButton();
        btn_suasanpham = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_bangsanpham = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_bangDSSanPham = new javax.swing.JTable();
        txt_timkiemdssanpham = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_Import = new javax.swing.JButton();
        btn_Export = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbo_tensanpham = new javax.swing.JComboBox<>();
        txt_serial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_gia = new javax.swing.JTextField();
        btn_lammoidssanpham = new javax.swing.JButton();
        btn_suasanpham1 = new javax.swing.JButton();
        btn_themsanpham1 = new javax.swing.JButton();
        btn_trangthai = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbo_CPU = new javax.swing.JComboBox<>();
        btn_themHang = new javax.swing.JButton();
        cbo_Card = new javax.swing.JComboBox<>();
        btn_themRam = new javax.swing.JButton();
        cbo_Ram = new javax.swing.JComboBox<>();
        btn_ThemCard = new javax.swing.JButton();
        cbo_Hang = new javax.swing.JComboBox<>();
        btn_themCPU = new javax.swing.JButton();
        cbo_OCung = new javax.swing.JComboBox<>();
        btn_themOCung = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1120, 660));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("THÔNG TIN SẢN PHẨM"));

        txt_tensanpham.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_tensanpham.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_tensanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tensanphamActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Tên sản phẩm:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Tìm kiếm:");

        btn_timkiemsanpham.setBackground(new java.awt.Color(255, 153, 102));
        btn_timkiemsanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/timkiem.png"))); // NOI18N
        btn_timkiemsanpham.setText("Tìm kiếm");

        btn_themsanpham.setBackground(new java.awt.Color(255, 153, 102));
        btn_themsanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/them.png"))); // NOI18N
        btn_themsanpham.setText("Thêm");

        btn_suasanpham.setBackground(new java.awt.Color(255, 153, 102));
        btn_suasanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/update (1).png"))); // NOI18N
        btn_suasanpham.setText("Sửa");

        tbl_bangsanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Mã Sản Phẩm", "Tên Sản Phẩm"
            }
        ));
        jScrollPane1.setViewportView(tbl_bangsanpham);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(28, 28, 28)
                                .addComponent(txt_tensanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txt_timkiemsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btn_timkiemsanpham)))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_suasanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_themsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1021, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_tensanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_themsanpham)
                        .addGap(11, 11, 11)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_timkiemsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_timkiemsanpham)
                            .addComponent(jLabel2)))
                    .addComponent(btn_suasanpham))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sản Phẩm", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "DANH SÁCH SẢN PHẨM"));

        tbl_bangDSSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên SP", "CPU", "Card", "Hãng", "Ổ Cứng", "Ram", "Serial", "Giá Bán", "Trạng Thái"
            }
        ));
        tbl_bangDSSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_bangDSSanPhamMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_bangDSSanPham);

        txt_timkiemdssanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timkiemdssanphamActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("Tìm kiếm:");

        btn_Import.setBackground(new java.awt.Color(255, 153, 102));
        btn_Import.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/excel.png"))); // NOI18N
        btn_Import.setText("Import");

        btn_Export.setBackground(new java.awt.Color(255, 153, 102));
        btn_Export.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/excel.png"))); // NOI18N
        btn_Export.setText("Export");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txt_timkiemdssanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(220, 220, 220)
                        .addComponent(btn_Import)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Export)))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_timkiemdssanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Import, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Export, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Chức Năng"));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setText("Tên SP:");

        txt_serial.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_serial.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_serial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_serialActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Serial:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Giá:");

        txt_gia.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_gia.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_gia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_giaActionPerformed(evt);
            }
        });

        btn_lammoidssanpham.setBackground(new java.awt.Color(255, 153, 102));
        btn_lammoidssanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/reset.png"))); // NOI18N
        btn_lammoidssanpham.setText("Làm Mới");
        btn_lammoidssanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lammoidssanphamActionPerformed(evt);
            }
        });

        btn_suasanpham1.setBackground(new java.awt.Color(255, 153, 102));
        btn_suasanpham1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/them.png"))); // NOI18N
        btn_suasanpham1.setText("Sửa");

        btn_themsanpham1.setBackground(new java.awt.Color(255, 153, 102));
        btn_themsanpham1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/them.png"))); // NOI18N
        btn_themsanpham1.setText("Thêm");

        btn_trangthai.setBackground(new java.awt.Color(255, 153, 102));
        btn_trangthai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/magnifier (1).png"))); // NOI18N
        btn_trangthai.setText("Trạng Thái");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbo_tensanpham, 0, 193, Short.MAX_VALUE)
                            .addComponent(txt_serial)
                            .addComponent(txt_gia)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_suasanpham1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_lammoidssanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_themsanpham1)
                            .addComponent(btn_trangthai))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbo_tensanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_serial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_lammoidssanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_themsanpham1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_suasanpham1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_trangthai, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Thuộc Tính"));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Hãng: ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Ram: ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Card: ");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setText("CPU: ");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setText("Ổ Cứng: ");

        cbo_CPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_CPUActionPerformed(evt);
            }
        });

        btn_themHang.setBackground(new java.awt.Color(255, 153, 102));
        btn_themHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/them.png"))); // NOI18N

        btn_themRam.setBackground(new java.awt.Color(255, 153, 102));
        btn_themRam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/them.png"))); // NOI18N
        btn_themRam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themRamActionPerformed(evt);
            }
        });

        btn_ThemCard.setBackground(new java.awt.Color(255, 153, 102));
        btn_ThemCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/them.png"))); // NOI18N
        btn_ThemCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemCardActionPerformed(evt);
            }
        });

        btn_themCPU.setBackground(new java.awt.Color(255, 153, 102));
        btn_themCPU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/them.png"))); // NOI18N
        btn_themCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themCPUActionPerformed(evt);
            }
        });

        cbo_OCung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_OCungActionPerformed(evt);
            }
        });

        btn_themOCung.setBackground(new java.awt.Color(255, 153, 102));
        btn_themOCung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/them.png"))); // NOI18N
        btn_themOCung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themOCungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(28, 28, 28)
                                .addComponent(cbo_CPU, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(btn_themCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(282, 282, 282)
                                .addComponent(btn_themOCung, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(cbo_Hang, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbo_Ram, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(111, 111, 111)
                                        .addComponent(jLabel10)
                                        .addGap(28, 28, 28)
                                        .addComponent(cbo_Card, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbo_OCung, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btn_themHang, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(251, 251, 251)
                        .addComponent(btn_themRam, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_ThemCard, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(237, 237, 237))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(cbo_Ram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cbo_Card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_Hang, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_themHang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_themRam, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ThemCard, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_CPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(cbo_OCung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_themCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_themOCung, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(74, 74, 74))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Chi Tiết Sản Phẩm", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void fillcomboboxram(){
        ramDAOImpl ramDAO = new ramDAOImpl();
List<ram> listRam = ramDAO.findAll();
DefaultComboBoxModel<ram> model = new DefaultComboBoxModel<>();
for (ram rm : listRam) {
    model.addElement(rm);
}
cbo_Ram.setModel(model);
    }
    public void fillComboBoxCPU() {
    cpuDAOImpl dao = new cpuDAOImpl();
    List<cpu> list = dao.findAll();
    DefaultComboBoxModel<cpu> model = new DefaultComboBoxModel<>();
    for (cpu item : list) {
        model.addElement(item);
    }
    cbo_CPU.setModel(model);
}
    public void fillComboBoxOCung() {
    ocungDAOImpl dao = new ocungDAOImpl();
    List<ocung> list = dao.findAll();
    DefaultComboBoxModel<ocung> model = new DefaultComboBoxModel<>();
    for (ocung item : list) {
        model.addElement(item);
    }
    cbo_OCung.setModel(model);
}
    public void fillComboBoxCard() {
    cardDAOImpl dao = new cardDAOImpl();
    List<card> list = dao.findAll();
    DefaultComboBoxModel<card> model = new DefaultComboBoxModel<>();
    for (card item : list) {
        model.addElement(item);
    }
    cbo_Card.setModel(model);
}
public void fillComboBoxHang() {
    hangDAOImpl dao = new hangDAOImpl();
    List<hang> list = dao.findAll();
    DefaultComboBoxModel<hang> model = new DefaultComboBoxModel<>();
    for (hang item : list) {
        model.addElement(item);
    }
    cbo_Hang.setModel(model);
}
private void fillTableChiTietSanPham() {
    DefaultTableModel model = (DefaultTableModel) tbl_bangDSSanPham.getModel();
    model.setRowCount(0); // Xóa dữ liệu cũ

    String sql = "SELECT * FROM v_chi_tiet_san_pham_display";

    try (
        Connection conn = XJdbc.openConnection();
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery()
    ) {
        int stt = 1;
        while (rs.next()) {
            Object[] row = {
                stt++,
                rs.getString("ten_san_pham"),
                rs.getString("ten_ram"),
                rs.getString("ten_cpu"),
                rs.getString("ten_ocung"),
                rs.getString("ten_card"),
                rs.getString("ten_hang"),
                rs.getString("serial"),
                rs.getDouble("gia_ban"),
                rs.getInt("trang_thai") == 1 ? "Còn hàng" : "Hết hàng"
            };
            model.addRow(row);
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu Chi Tiết Sản Phẩm: " + e.getMessage());
    }
}



    
    private void txt_tensanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tensanphamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tensanphamActionPerformed

    private void txt_serialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_serialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_serialActionPerformed

    private void txt_giaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_giaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_giaActionPerformed

    private void btn_lammoidssanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lammoidssanphamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_lammoidssanphamActionPerformed

    private void cbo_CPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_CPUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_CPUActionPerformed

    private void cbo_OCungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_OCungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_OCungActionPerformed

    private void txt_timkiemdssanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timkiemdssanphamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timkiemdssanphamActionPerformed

    private void btn_themCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themCPUActionPerformed
    JFrame parent = (JFrame) SwingUtilities.getWindowAncestor(this);
    cpujDialog dialog = new cpujDialog(parent, true);
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);
    }//GEN-LAST:event_btn_themCPUActionPerformed

    private void btn_themRamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themRamActionPerformed
        // TODO add your handling code here:
    JFrame parent = (JFrame) SwingUtilities.getWindowAncestor(this);
    ramJDialog dialog = new ramJDialog(parent, true);
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);
    }//GEN-LAST:event_btn_themRamActionPerformed

    private void btn_themOCungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themOCungActionPerformed
        // TODO add your handling code here:
    JFrame parent = (JFrame) SwingUtilities.getWindowAncestor(this);
    ocungJDialog dialog = new ocungJDialog(parent, true);
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);
    }//GEN-LAST:event_btn_themOCungActionPerformed

    private void btn_ThemCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemCardActionPerformed
        // TODO add your handling code here:
    JFrame parent = (JFrame) SwingUtilities.getWindowAncestor(this);
    cardJDialog dialog = new cardJDialog(parent, true);
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);
    }//GEN-LAST:event_btn_ThemCardActionPerformed

    private void tbl_bangDSSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bangDSSanPhamMouseClicked
        int row = tbl_bangDSSanPham.getSelectedRow();
    if (row >= 0) {
        cbo_tensanpham.setSelectedItem(tbl_bangDSSanPham.getValueAt(row, 1));
        cbo_Ram.setSelectedItem(tbl_bangDSSanPham.getValueAt(row, 2));
        cbo_CPU.setSelectedItem(tbl_bangDSSanPham.getValueAt(row, 3));
        cbo_OCung.setSelectedItem(tbl_bangDSSanPham.getValueAt(row, 4));
        cbo_Card.setSelectedItem(tbl_bangDSSanPham.getValueAt(row, 5));
        cbo_Hang.setSelectedItem(tbl_bangDSSanPham.getValueAt(row, 6));
        txt_serial.setText(String.valueOf(tbl_bangDSSanPham.getValueAt(row, 7)));
        txt_gia.setText(String.valueOf(tbl_bangDSSanPham.getValueAt(row, 8)));
        // Nếu trạng thái là combobox hoặc button, bạn có thể xử lý như sau:
        String trangThai = String.valueOf(tbl_bangDSSanPham.getValueAt(row, 9));
        btn_trangthai.setText(trangThai); // Nếu là nút, hoặc setSelectedItem nếu là combobox
    }
}//GEN-LAST:event_tbl_bangDSSanPhamMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Export;
    private javax.swing.JButton btn_Import;
    private javax.swing.JButton btn_ThemCard;
    private javax.swing.JButton btn_lammoidssanpham;
    private javax.swing.JButton btn_suasanpham;
    private javax.swing.JButton btn_suasanpham1;
    private javax.swing.JButton btn_themCPU;
    private javax.swing.JButton btn_themHang;
    private javax.swing.JButton btn_themOCung;
    private javax.swing.JButton btn_themRam;
    private javax.swing.JButton btn_themsanpham;
    private javax.swing.JButton btn_themsanpham1;
    private javax.swing.JButton btn_timkiemsanpham;
    private javax.swing.JButton btn_trangthai;
    private javax.swing.JComboBox<cpu> cbo_CPU;
    private javax.swing.JComboBox<card> cbo_Card;
    private javax.swing.JComboBox<hang> cbo_Hang;
    private javax.swing.JComboBox<ocung> cbo_OCung;
    private javax.swing.JComboBox<ram> cbo_Ram;
    private javax.swing.JComboBox<String> cbo_tensanpham;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbl_bangDSSanPham;
    private javax.swing.JTable tbl_bangsanpham;
    private javax.swing.JTextField txt_gia;
    private javax.swing.JTextField txt_serial;
    private javax.swing.JTextField txt_tensanpham;
    private javax.swing.JTextField txt_timkiemdssanpham;
    private javax.swing.JTextField txt_timkiemsanpham;
    // End of variables declaration//GEN-END:variables
}
