/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package DellStore.ui.JDialog;

import DellStore.dao.impl.cardDAOImpl;
import DellStore.dao.impl.chitietsanphamDAO;
import DellStore.dao.impl.cpuDAOImpl;
import DellStore.dao.impl.ocungDAOImpl;
import DellStore.dao.impl.ramDAOImpl;
import DellStore.dao.impl.sanphamDAO;
import DellStore.entity.Card;
import DellStore.entity.ChiTietSanPham;
import DellStore.entity.Cpu;
import DellStore.entity.Ocung;
import DellStore.entity.Ram;
import DellStore.entity.SanPham;
import DellStore.entity.Serial;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.Vector;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

public class ChiTietSanPhamJDialog extends javax.swing.JDialog {

    private cpuDAOImpl cpuDAO = new cpuDAOImpl();
    private ramDAOImpl ramDAO = new ramDAOImpl();
    private ocungDAOImpl ssdDAO = new ocungDAOImpl();
    private cardDAOImpl gpuDAO = new cardDAOImpl();
    private sanphamDAO spDAO = new sanphamDAO();
    private SanPham sp;
    private int soLuong; // số lượng sản phẩm đã nhập ở bước 1
    private List<Cpu> listCPU;
    private List<Ram> listRAM;
    private List<Ocung> listSSD;
    private List<Card> listGPU;
    private List<ChiTietSanPham> listChiTietSP = new ArrayList<>();
    private DefaultTableModel model;
    private List<SanPham> listSanPham;

    /**
     * Creates new form ChiTietSanPhamJDialog
     */
    public ChiTietSanPhamJDialog(java.awt.Frame parent, boolean modal, SanPham sp, List<SanPham> listSanPham,
            List<Cpu> listCPU, List<Ram> listRAM, List<Ocung> listSSD, List<Card> listGPU, int soLuong) {
        super(parent, modal);
        initComponents(); // Netbeans tạo
        setLocationRelativeTo(null);
        this.sp = sp;
        this.soLuong = soLuong;
        this.listCPU = listCPU;
        this.listRAM = listRAM;
        this.listSSD = listSSD;
        this.listGPU = listGPU;
        this.listSanPham = listSanPham;
        initTable();
    }

    private void initTable() {
        model = (DefaultTableModel) tbl_thongso.getModel();
        model.setRowCount(0);

            model.addRow(new Object[]{1, "", "", "", "", "", ""});

        JComboBox<String> cbCPU = new JComboBox<>();
        for (Cpu cpu : listCPU) {
            cbCPU.addItem(cpu.getTen());
        }
        tbl_thongso.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(cbCPU));

        JComboBox<String> cbRAM = new JComboBox<>();
        for (Ram ram : listRAM) {
            cbRAM.addItem(ram.getDung_luong());
        }
        tbl_thongso.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(cbRAM));

        JComboBox<String> cbSSD = new JComboBox<>();
        for (Ocung ssd : listSSD) {
            cbSSD.addItem(ssd.getDung_luong());
        }
        tbl_thongso.getColumnModel().getColumn(4).setCellEditor(new DefaultCellEditor(cbSSD));

        JComboBox<String> cbGPU = new JComboBox<>();
        for (Card gpu : listGPU) {
            cbGPU.addItem(gpu.getTen());
        }
        tbl_thongso.getColumnModel().getColumn(5).setCellEditor(new DefaultCellEditor(cbGPU));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_lammoi = new javax.swing.JButton();
        btn_huy = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_thongso = new javax.swing.JTable();
        btn_themdong = new javax.swing.JButton();
        btn_luu = new javax.swing.JButton();
        btn_apdungtoanbo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("🖥️  THÊM CHI TIẾT SẢN PHẨM");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_lammoi.setText("Làm mới dòng");
        btn_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lammoiActionPerformed(evt);
            }
        });

        btn_huy.setText("Hủy");
        btn_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyActionPerformed(evt);
            }
        });

        tbl_thongso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Số Lượng", "CPU", "RAM", "SSD", "GPU", "Gia Ban"
            }
        ));
        jScrollPane1.setViewportView(tbl_thongso);

        btn_themdong.setText("Thêm dòng");
        btn_themdong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themdongActionPerformed(evt);
            }
        });

        btn_luu.setText("Lưu");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        btn_apdungtoanbo.setText("Áp Dụng Cho Toàn Bộ");
        btn_apdungtoanbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_apdungtoanboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_themdong)
                        .addGap(40, 40, 40)
                        .addComponent(btn_lammoi)
                        .addGap(34, 34, 34)
                        .addComponent(btn_apdungtoanbo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_huy)
                        .addGap(43, 43, 43)
                        .addComponent(btn_luu)
                        .addGap(123, 123, 123)))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_themdong)
                    .addComponent(btn_lammoi)
                    .addComponent(btn_apdungtoanbo))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_huy)
                    .addComponent(btn_luu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyActionPerformed
        // Xác nhận trước khi huỷ
    int confirm = JOptionPane.showConfirmDialog(
        this, 
        "Bạn có chắc muốn huỷ? Tất cả dữ liệu sẽ bị xoá.", 
        "Xác nhận huỷ", 
        JOptionPane.YES_NO_OPTION
    );
    
    if (confirm == JOptionPane.YES_OPTION) {
        // Xoá toàn bộ dữ liệu trong bảng tbl_thongso
        DefaultTableModel model = (DefaultTableModel) tbl_thongso.getModel();
        model.setRowCount(0);

        // Xoá danh sách tạm lưu chi tiết sản phẩm
        listChiTietSP.clear();

        // Nếu bảng sản phẩm chính có lưu tạm sản phẩm vừa tạo, xoá luôn
        // (chỗ này tuỳ thuộc bạn đang lưu sản phẩm ở đâu)
        // productDAO.deleteTempProduct(currentProductId);

        // Đóng form
        dispose();
    }
    }//GEN-LAST:event_btn_huyActionPerformed

    private void btn_apdungtoanboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_apdungtoanboActionPerformed
        if (tbl_thongso.getRowCount() == 0) {
            return;
        }

        Object cpu = tbl_thongso.getValueAt(0, 2);
        Object ram = tbl_thongso.getValueAt(0, 3);
        Object ssd = tbl_thongso.getValueAt(0, 4);
        Object gpu = tbl_thongso.getValueAt(0, 5);
        Object gia = tbl_thongso.getValueAt(0, 6);

        for (int i = 1; i < tbl_thongso.getRowCount(); i++) {
            tbl_thongso.setValueAt(cpu, i, 2);
            tbl_thongso.setValueAt(ram, i, 3);
            tbl_thongso.setValueAt(ssd, i, 4);
            tbl_thongso.setValueAt(gpu, i, 5);
            tbl_thongso.setValueAt(gia, i, 6);
        }
    }//GEN-LAST:event_btn_apdungtoanboActionPerformed
    public String getThongSoText(Cpu cpu, Ram ram, Ocung ssd, Card gpu) {
        return cpu.getTen() + " / " + ram.getDung_luong() + " / " + ssd.getDung_luong() + " / " + gpu.getTen();
    }

    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
 listChiTietSP.clear();
int idSanPham = sp.getId();

//if (idSanPham <= 0) {
//    JOptionPane.showMessageDialog(this, "Lỗi: Sản phẩm chưa được lưu vào cơ sở dữ liệu.");
//    return;
//}

int tongSoLuong = 0;
Set<String> uniqueConfigs = new HashSet<>();
Set<BigDecimal> uniquePrices = new HashSet<>();

// ====== Bước 1: Kiểm tra dữ liệu ======
for (int i = 0; i < tbl_thongso.getRowCount(); i++) {
    // 1. Kiểm tra số lượng
    Object soLuongObj = tbl_thongso.getValueAt(i, 1);
    if (soLuongObj == null) continue;

    int soLuong;
    try {
        soLuong = Integer.parseInt(soLuongObj.toString());
        if (soLuong <= 0) {
            JOptionPane.showMessageDialog(this, "Số lượng phải > 0 tại dòng " + (i + 1));
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Số lượng không hợp lệ tại dòng " + (i + 1));
        return;
    }
    tongSoLuong += soLuong;

    // 2. Lấy dữ liệu cấu hình
    String cpuName = (String) tbl_thongso.getValueAt(i, 2);
    String ramSize = (String) tbl_thongso.getValueAt(i, 3);
    String ssdSize = (String) tbl_thongso.getValueAt(i, 4);
    String gpuName = (String) tbl_thongso.getValueAt(i, 5);
    Object giaObj = tbl_thongso.getValueAt(i, 6);

    if (cpuName == null || ramSize == null || ssdSize == null || gpuName == null || giaObj == null) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ dữ liệu ở dòng " + (i + 1));
        return;
    }

    // 3. Kiểm tra trùng cấu hình
    String configKey = cpuName.trim() + "|" + ramSize.trim() + "|" + ssdSize.trim() + "|" + gpuName.trim();
    if (uniqueConfigs.contains(configKey)) {
        JOptionPane.showMessageDialog(this, "Cấu hình tại dòng " + (i + 1) + " bị trùng với một dòng khác.");
        return;
    }
    uniqueConfigs.add(configKey);

    // 4. Kiểm tra giá bán hợp lệ
    BigDecimal giaBan;
    try {
        giaBan = new BigDecimal(giaObj.toString().trim());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Giá bán không hợp lệ tại dòng " + (i + 1));
        return;
    }

    // 5. Kiểm tra trùng giá bán
    if (uniquePrices.stream().anyMatch(g -> g.compareTo(giaBan) == 0)) {
        JOptionPane.showMessageDialog(this, "Giá bán tại dòng " + (i + 1) + " bị trùng với một dòng khác.");
        return;
    }
    uniquePrices.add(giaBan);
}

// Kiểm tra tổng số lượng
if (tongSoLuong != soLuong) {
    JOptionPane.showMessageDialog(this, "Tổng số lượng nhập vào phải bằng " + soLuong + " sản phẩm.");
    return;
}

// ====== Bước 2: Tạo danh sách chi tiết sản phẩm ======
for (int i = 0; i < tbl_thongso.getRowCount(); i++) {
    int soLuongNhap = Integer.parseInt(tbl_thongso.getValueAt(i, 1).toString());
    String cpuName = (String) tbl_thongso.getValueAt(i, 2);
    String ramSize = (String) tbl_thongso.getValueAt(i, 3);
    String ssdSize = (String) tbl_thongso.getValueAt(i, 4);
    String gpuName = (String) tbl_thongso.getValueAt(i, 5);
    BigDecimal giaBan = new BigDecimal(tbl_thongso.getValueAt(i, 6).toString().trim());

    Cpu cpu = listCPU.stream().filter(c -> c.getTen().trim().equals(cpuName.trim())).findFirst().orElse(null);
    Ram ram = listRAM.stream().filter(r -> r.getDung_luong().trim().equals(ramSize.trim())).findFirst().orElse(null);
    Ocung ssd = listSSD.stream().filter(s -> s.getDung_luong().trim().equals(ssdSize.trim())).findFirst().orElse(null);
    Card gpu = listGPU.stream().filter(g -> g.getTen().trim().equals(gpuName.trim())).findFirst().orElse(null);

    if (cpu == null || ram == null || ssd == null || gpu == null) {
        JOptionPane.showMessageDialog(this, "Cài đặt cấu hình không hợp lệ tại dòng " + (i + 1));
        return;
    }

    for (int j = 0; j < soLuongNhap; j++) {
        ChiTietSanPham ctsp = new ChiTietSanPham();
        ctsp.setSan_pham_id(idSanPham);
        ctsp.setCpu_id(cpu.getId());
        ctsp.setRam_id(ram.getId());
        ctsp.setSsd_id(ssd.getId());
        ctsp.setGpu_id(gpu.getId());
        ctsp.setGia_ban(giaBan);
        ctsp.setTrang_thai(0);
        listChiTietSP.add(ctsp);
    }
}

JOptionPane.showMessageDialog(this, "Tổng " + listChiTietSP.size() + " chi tiết sản phẩm đã được tạo.");
this.dispose();
    }//GEN-LAST:event_btn_luuActionPerformed

    private void btn_themdongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themdongActionPerformed
        // TODO add your handling code here:
          int stt = tbl_thongso.getRowCount() + 1;
    DefaultTableModel model = (DefaultTableModel) tbl_thongso.getModel();
    model.addRow(new Object[]{stt, "", "", "", "", "", ""});
    }//GEN-LAST:event_btn_themdongActionPerformed

    private void btn_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lammoiActionPerformed
        // TODO add your handling code here:
          int selectedRow = tbl_thongso.getSelectedRow();
    if (selectedRow != -1) { // Có dòng được chọn
        DefaultTableModel model = (DefaultTableModel) tbl_thongso.getModel();
        model.removeRow(selectedRow);
    } else {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để xoá.");
    }
    }//GEN-LAST:event_btn_lammoiActionPerformed

    public void setData(List<SanPham> listSanPham) {
        model.setRowCount(0);
        for (SanPham sp : listSanPham) {
            model.addRow(new Object[]{sp, null, null, null, null, null});
        }
    }

    public List<ChiTietSanPham> getChiTietList() {
        return listChiTietSP;
    }

    public void setListSanPham(List<SanPham> listSanPham) {
        this.listSanPham = listSanPham;
    }

// ...existing code...

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_apdungtoanbo;
    private javax.swing.JButton btn_huy;
    private javax.swing.JButton btn_lammoi;
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_themdong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_thongso;
    // End of variables declaration//GEN-END:variables
// ...existing code...
}
