package DellStore.ui.JDialog;

import DellStore.dao.impl.ChiTietHoaDonDAOImpl;
import DellStore.dao.impl.SerialDAOImpl;
import DellStore.dao.impl.chitietsanphamDAO;
import DellStore.entity.ChiTietHoaDon;
import DellStore.entity.ChiTietSanPham;
import DellStore.entity.SanPham;
//import java.io.Serial;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

import java.util.List;

import DellStore.entity.Serial;
import java.math.BigDecimal;
import javax.swing.JOptionPane;

public class ChonSerialJDialog extends javax.swing.JDialog {

    private List<Serial> selectedSerials = new ArrayList<>();
    private SerialDAOImpl serialDAO = new SerialDAOImpl();
    private chitietsanphamDAO ctspDAO = new chitietsanphamDAO();
    private int hoaDonId;
    private ChiTietHoaDonDAOImpl cthdDAO = new ChiTietHoaDonDAOImpl();
    private int hoaDonDangTaoId;

    /**
     * Creates new form ChonSerialJDialog
     */
    public ChonSerialJDialog(java.awt.Frame parent, boolean modal, int hoaDonDangTaoId) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.hoaDonId = hoaDonId;
        this.hoaDonDangTaoId = hoaDonDangTaoId;

    }

   public void loadTable(SanPham sp, List<Serial> listSerial) {
    // Khởi tạo model mới với tiêu đề chuẩn
    DefaultTableModel model = new DefaultTableModel(
        new Object[]{"Chọn", "Mã SP", "Tên SP", "Serial",
                     "SAN_PHAM_ID", "CPU_ID", "RAM_ID", "SSD_ID", "GPU_ID"}, 0
    ) {
        @Override
        public Class<?> getColumnClass(int columnIndex) {
            return columnIndex == 0 ? Boolean.class : Object.class;
        }

        @Override
        public boolean isCellEditable(int row, int column) {
            return column == 0; // chỉ cho tick checkbox
        }
    };

    // Đổ dữ liệu
    for (Serial s : listSerial) {
        ChiTietSanPham ctsp = ctspDAO.findById(s.getCtsp_id());
        if (ctsp != null) {
            model.addRow(new Object[]{
                false,
                sp.getMasp(),
                sp.getTen(),
                s.getMa_serial(),
                ctsp.getSan_pham_id(),
                ctsp.getCpu_id(),
                ctsp.getRam_id(),
                ctsp.getSsd_id(),
                ctsp.getGpu_id()
            });
        }
    }

    // Set model mới cho bảng
    tbl_bang.setModel(model);

    // Ẩn các cột thông số
    int[] hiddenCols = {4, 5, 6, 7, 8};
    for (int col : hiddenCols) {
        tbl_bang.getColumnModel().getColumn(col).setMinWidth(0);
        tbl_bang.getColumnModel().getColumn(col).setMaxWidth(0);
        tbl_bang.getColumnModel().getColumn(col).setWidth(0);
        tbl_bang.getColumnModel().getColumn(col).setPreferredWidth(0);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_bang = new javax.swing.JTable();
        btn_xacnhan = new javax.swing.JButton();
        btn_huy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbl_bang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "", "MaSP", "TenSP", "MaSerial", "Title 5"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_bang);

        btn_xacnhan.setText("Xác Nhận");
        btn_xacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xacnhanActionPerformed(evt);
            }
        });

        btn_huy.setText("Hủy");
        btn_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(btn_xacnhan)
                .addGap(101, 101, 101)
                .addComponent(btn_huy)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_xacnhan)
                    .addComponent(btn_huy))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_xacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xacnhanActionPerformed
       selectedSerials.clear();
    DefaultTableModel model = (DefaultTableModel) tbl_bang.getModel();

    for (int i = 0; i < model.getRowCount(); i++) {
        Boolean isChecked = (Boolean) model.getValueAt(i, 0);
        if (isChecked != null && isChecked) {
            String serialStr = model.getValueAt(i, 3).toString();

            Serial s = serialDAO.findByMaSerial(serialStr);
            if (s != null) {
                // Check trùng: đã có Serial này trong giỏ (cthd) chưa?
                ChiTietSanPham ctsp = ctspDAO.findBySerialId(s.getId());

                if (ctsp != null && hoaDonDangTaoId != -1) {
                    ChiTietHoaDon cthdCu = cthdDAO.findByHoaDonAndCTSP(hoaDonDangTaoId, ctsp.getId());

                    if (cthdCu != null) {
                        // ❌ Trùng → bỏ qua hoặc thông báo
                        JOptionPane.showMessageDialog(this, "⚠️ Serial đã được chọn trước đó: " + serialStr);
                        continue;
                    }

                    // ✅ Chưa có → thêm mới vào chi tiết hóa đơn
                    ChiTietHoaDon cthd = new ChiTietHoaDon();
                    cthd.setHoa_don_id(hoaDonDangTaoId);
                    cthd.setChi_tiet_san_pham_id(ctsp.getId());
                    cthd.setSo_luong(1); // mỗi Serial chỉ 1 sản phẩm
                    cthd.setDon_gia(ctsp.getGia_ban());
                    cthd.setGiam_gia(BigDecimal.ZERO);
                    cthd.setTrang_thai(0);               
                    cthdDAO.insert(cthd);

                    // 🔄 Update trạng thái Serial sang "đang giữ" (2)
                    s.setTrang_thai(2);
                    serialDAO.updateTrangThai(s.getId(), s.getTrang_thai());

                    selectedSerials.add(s); // lưu Serial đã chọn
                    
                } else {
                    System.out.println("❌ Không thể lưu: ctsp = null hoặc hoaDonDangTaoId = -1");
                }
            }
        }
    }

    dispose(); // đóng dialog sau khi chọn xong
    }//GEN-LAST:event_btn_xacnhanActionPerformed

    private void btn_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyActionPerformed
        // TODO add your handling code here:
        selectedSerials.clear(); // Không chọn gì cả
        dispose();
    }//GEN-LAST:event_btn_huyActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChonSerialJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChonSerialJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChonSerialJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChonSerialJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ChonSerialJDialog dialog = new ChonSerialJDialog(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_huy;
    private javax.swing.JButton btn_xacnhan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_bang;
    // End of variables declaration//GEN-END:variables
public List<Serial> getSelectedSerials() {
        return selectedSerials;
    }


}
