/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package DellStore.ui.JDialog;

import DellStore.dao.impl.ChiTietHoaDonDAOImpl;
import DellStore.dao.impl.KhuyenMaiDAOImpl;
import DellStore.dao.impl.SerialDAOImpl;
import DellStore.dao.impl.chitietsanphamDAO;
import DellStore.entity.SanPhamChiTietViewModel;
import DellStore.entity.Serial;
import DellStore.ui.manager.SanPhamJPanel;
import DellStore.utils.XJdbc;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.*;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;
import java.util.stream.Collectors;

/**
 *
 * @author docon
 */
public class DialogChonChiTietSP extends javax.swing.JDialog {

    private List<SanPhamChiTietViewModel> dataList;  // danh sách gốc truyền từ panel
    private List<SanPhamChiTietViewModel> currentList; // danh sách đang hiển thị
    private SanPhamChiTietViewModel selectedItem;
    private SerialDAOImpl serialDAO = new SerialDAOImpl();
    private ChiTietHoaDonDAOImpl cthdDAO = new ChiTietHoaDonDAOImpl();
    private KhuyenMaiDAOImpl ctdggDAO = new KhuyenMaiDAOImpl();
    private chitietsanphamDAO ctspDAO = new chitietsanphamDAO();

    /**
     * Creates new form DialogChonChiTietSP
     */
    public DialogChonChiTietSP(java.awt.Frame parent, boolean modal, List<SanPhamChiTietViewModel> list) {
        super(parent, modal);
        initComponents();
        this.dataList = list;
        fillTable(dataList);
        setLocationRelativeTo(parent);

        // Nhóm radio
        ButtonGroup group = new ButtonGroup();
        group.add(rdo_tatca);
        group.add(rdo_dangban);
        group.add(rdo_daban);
    }

    private void fillTable(List<SanPhamChiTietViewModel> list) {
        DefaultTableModel model = (DefaultTableModel) tbl_bang.getModel();
        model.setRowCount(0);
        for (SanPhamChiTietViewModel sp : list) {
            model.addRow(new Object[]{
                sp.getId(),
                sp.getTenSanPham(),
                sp.getCpu(),
                sp.getCard(),
                sp.getHang(),
                sp.getOcung(),
                sp.getRam(),
                sp.getSerial(),
                sp.getGiaBan(),
                sp.getTrangThai() == 0 ? "Đang bán" : "Đã bán"
            });
        }
    }

    private void filterData() {
        String keyword = txt_timkiemserial.getText().trim().toLowerCase();
        List<SanPhamChiTietViewModel> filtered = dataList.stream()
                .filter(sp -> sp.getSerial().toLowerCase().contains(keyword))
                .filter(sp -> {
                    if (rdo_dangban.isSelected()) {
                        return sp.getTrangThai() == 0;
                    }
                    if (rdo_daban.isSelected()) {
                        return sp.getTrangThai() == 1;
                    }
                    return true; // tất cả
                })
                .collect(Collectors.toList());

        fillTable(filtered);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rdo_tatca = new javax.swing.JRadioButton();
        rdo_dangban = new javax.swing.JRadioButton();
        rdo_daban = new javax.swing.JRadioButton();
        txt_timkiemserial = new javax.swing.JTextField();
        btn_timkiem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_bang = new javax.swing.JTable();
        btn_xacnhan = new javax.swing.JButton();
        btn_huy = new javax.swing.JButton();
        btn_xoaSP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chọn Chi Tiết Sản Phẩm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tìm Kiếm Serial:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Trạng Thái:");

        rdo_tatca.setText("Tất Cả");
        rdo_tatca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_tatcaActionPerformed(evt);
            }
        });

        rdo_dangban.setText("Đang Bán");
        rdo_dangban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_dangbanActionPerformed(evt);
            }
        });

        rdo_daban.setText("Đã Bán");
        rdo_daban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_dabanActionPerformed(evt);
            }
        });

        btn_timkiem.setText("Tìm Kiếm");
        btn_timkiem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdo_tatca, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdo_dangban, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdo_daban, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_timkiemserial, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btn_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_timkiemserial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdo_tatca)
                    .addComponent(rdo_dangban)
                    .addComponent(rdo_daban))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi Tiết Sản Phẩm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        tbl_bang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên SP", "CPU", "Card", "Hãng", "Ổ Cứng", "Ram", "Serial", "Giá Bán", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_bang);

        btn_xacnhan.setText("Xác Nhận");
        btn_xacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xacnhanActionPerformed(evt);
            }
        });

        btn_huy.setText("Hủy");
        btn_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyActionPerformed(evt);
            }
        });

        btn_xoaSP.setText("Xóa SP");
        btn_xoaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(btn_xacnhan)
                .addGap(76, 76, 76)
                .addComponent(btn_xoaSP)
                .addGap(64, 64, 64)
                .addComponent(btn_huy)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_xacnhan)
                    .addComponent(btn_huy)
                    .addComponent(btn_xoaSP))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(169, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdo_dabanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_dabanActionPerformed
        // TODO add your handling code here:
        filterData();
    }//GEN-LAST:event_rdo_dabanActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        // TODO add your handling code here:
        filterData();
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void rdo_tatcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_tatcaActionPerformed
        // TODO add your handling code here:
        filterData();
    }//GEN-LAST:event_rdo_tatcaActionPerformed

    private void rdo_dangbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_dangbanActionPerformed
        // TODO add your handling code here:
        filterData();
    }//GEN-LAST:event_rdo_dangbanActionPerformed

    private void btn_xacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xacnhanActionPerformed
        int row = tbl_bang.getSelectedRow();
        if (row >= 0) {
            // Kiểm tra toàn bộ cột để đảm bảo không null
            for (int col = 0; col < tbl_bang.getColumnCount(); col++) {
                Object value = tbl_bang.getValueAt(row, col);
                if (value == null || value.toString().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this,
                            "Dữ liệu tại cột " + tbl_bang.getColumnName(col) + " đang trống!",
                            "Thiếu dữ liệu", JOptionPane.WARNING_MESSAGE);
                    return; // Thoát luôn, không xử lý tiếp
                }
            }

            selectedItem = new SanPhamChiTietViewModel();
            selectedItem.setId(Integer.parseInt(tbl_bang.getValueAt(row, 0).toString()));
            selectedItem.setTenSanPham(tbl_bang.getValueAt(row, 1).toString());
            selectedItem.setCpu(tbl_bang.getValueAt(row, 2).toString());
            selectedItem.setCard(tbl_bang.getValueAt(row, 3).toString());
            selectedItem.setHang(tbl_bang.getValueAt(row, 4).toString());
            selectedItem.setOcung(tbl_bang.getValueAt(row, 5).toString());
            selectedItem.setRam(tbl_bang.getValueAt(row, 6).toString());
            selectedItem.setSerial(tbl_bang.getValueAt(row, 7).toString());
            selectedItem.setGiaBan(new BigDecimal(tbl_bang.getValueAt(row, 8).toString()));

            String ttStr = tbl_bang.getValueAt(row, 9).toString();
            int tt = ttStr.equalsIgnoreCase("Đang Bán") ? 0 : 1;
            selectedItem.setTrangThai(tt);

            dispose(); // đóng dialog
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một sản phẩm!");
        }
    }//GEN-LAST:event_btn_xacnhanActionPerformed

    private void btn_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyActionPerformed
        // TODO add your handling code here:
        selectedItem = null;
        dispose();
    }//GEN-LAST:event_btn_huyActionPerformed

    private void btn_xoaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaSPActionPerformed
        int row = tbl_bang.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một sản phẩm để xóa!");
            return;
        }

        int ctspId = Integer.parseInt(tbl_bang.getValueAt(row, 0).toString()); // cột 0 = ctspId
        String maSerial = tbl_bang.getValueAt(row, 7).toString(); // cột 7 = Serial

        int confirm = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc muốn xóa sản phẩm này?\nLưu ý: Các bản ghi liên quan sẽ bị xóa theo cascade nếu có.",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        Connection conn = null;
        try {
            conn = XJdbc.openConnection();
            conn.setAutoCommit(false);

            // 1. Xóa Serial trước
            String sqlSerial = "DELETE FROM serial WHERE ctsp_id = ?";
            try (PreparedStatement ps = conn.prepareStatement(sqlSerial)) {
                ps.setInt(1, ctspId);
                ps.executeUpdate();
            }

            // 2. Xóa chi_tiet_dot_giam_gia trước (cascade sẽ xóa chi_tiet_hoa_don)
            String sqlCTDGG = "DELETE FROM chi_tiet_dot_giam_gia WHERE ctsp_id = ?";
            try (PreparedStatement ps = conn.prepareStatement(sqlCTDGG)) {
                ps.setInt(1, ctspId);
                ps.executeUpdate();
            }

            // 3. Xóa chi_tiet_san_pham
            String sqlCTSP = "DELETE FROM chi_tiet_san_pham WHERE id = ?";
            try (PreparedStatement ps = conn.prepareStatement(sqlCTSP)) {
                ps.setInt(1, ctspId);
                ps.executeUpdate();
            }

            // Commit transaction
            conn.commit();

            // 4. Cập nhật dialog
            dataList.removeIf(sp -> sp.getSerial().equals(maSerial));
            fillTable(dataList);

            JOptionPane.showMessageDialog(this, "Đã xóa sản phẩm thành công!");
        } catch (Exception e) {
            try {
                if (conn != null) {
                    conn.rollback();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            JOptionPane.showMessageDialog(this, "Xóa thất bại: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_xoaSPActionPerformed
    public SanPhamChiTietViewModel getSelectedItem() {
        return selectedItem;
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DialogChonChiTietSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DialogChonChiTietSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DialogChonChiTietSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DialogChonChiTietSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DialogChonChiTietSP dialog = new DialogChonChiTietSP(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_huy;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JButton btn_xacnhan;
    private javax.swing.JButton btn_xoaSP;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdo_daban;
    private javax.swing.JRadioButton rdo_dangban;
    private javax.swing.JRadioButton rdo_tatca;
    private javax.swing.JTable tbl_bang;
    private javax.swing.JTextField txt_timkiemserial;
    // End of variables declaration//GEN-END:variables
}
