/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DellStore.ui;

import DellStore.ui.manager.NhanVienJPanel;
import DellStore.ui.manager.HomeJPanel;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import DellStore.ui.manager.KhachHangJPanel;
import DellStore.ui.manager.KhuyenMaiJPanel;
import DellStore.ui.manager.SanPhamJPanel;
import DellStore.ui.manager.ThongKeJPanel;
import DellStore.ui.manager.BanHangJPanel;
import DellStore.ui.manager.HoaDonJPanel;
import DellStore.controller.DellStoreController;
import DellStore.entity.NhanVien;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Gigabyte
 */
public class DellStoreJFrame extends javax.swing.JFrame implements DellStoreController{
 public NhanVien nvLogin;
    /**
     * Creates new form Form
     */
    public void showPanel(javax.swing.JPanel panel) {

        pnlCCenter.removeAll();                   // Xóa panel cũ
        pnlCCenter.setLayout(new java.awt.BorderLayout());
        pnlCCenter.add(panel, java.awt.BorderLayout.CENTER);
        pnlCCenter.revalidate();                 // Cập nhật lại giao diện
        pnlCCenter.repaint();

    }

    public DellStoreJFrame(NhanVien nvLogin) {
        initComponents();
        this.nvLogin = nvLogin;
        this.pack();
        phanQuyen(); 
        setLocationRelativeTo(null);
//        this.showWelcomeJDialog(this);
//        this.showLoginDialog(this);
        init();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);  // FULLSCREE
        JButton[] btns = {btn_thongke, btn_khachhang, btn_nhanvien, btn_khuyenmai, btn_sanpham, btn_banhang, btn_hoadon,btn_thoat};
        for (JButton btn : btns) {
            btn.setOpaque(true); // QUAN TRỌNG: cho phép vẽ nền đúng
            btn.setBorderPainted(false);
            btn.setFocusPainted(false);
            btn.setContentAreaFilled(false);
            btn.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    //   throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                @Override
                public void mousePressed(MouseEvent e) {
                    //  throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                    //   throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    //  throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                    btn.setOpaque(true);
                    btn.setBackground(new Color(255, 183, 77));

                }

                @Override
                public void mouseExited(MouseEvent e) {
                    // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                    btn.setOpaque(true);
                    btn.setBackground(new Color(14, 36, 49));

                }
            });

        }
    }
    private void phanQuyen() {
        System.out.println("Chức vụ đăng nhập: " + nvLogin.getChuc_vu());
    if (nvLogin == null) {
        JOptionPane.showMessageDialog(this, "Không có người dùng đăng nhập!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        System.exit(0);
        return;
    }

    String chucVu = nvLogin.getChuc_vu() != null ? nvLogin.getChuc_vu().trim() : "";

    if (chucVu.equalsIgnoreCase("Nhân viên")) {
      btn_sanpham.setVisible(false);
btn_nhanvien.setVisible(false);
btn_khuyenmai.setVisible(false);
btn_thongke.setVisible(false);

    }

    lblTenNhanVien.setText("Xin chào: " + nvLogin.getTen_nv());
    lblChucVu.setText("Chức vụ: " + chucVu);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();
        pnlSlide = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btn_banhang = new javax.swing.JButton();
        btn_sanpham = new javax.swing.JButton();
        btn_nhanvien = new javax.swing.JButton();
        btn_hoadon = new javax.swing.JButton();
        btn_khuyenmai = new javax.swing.JButton();
        btn_khachhang = new javax.swing.JButton();
        btn_thongke = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();
        pnlCenter = new javax.swing.JPanel();
        pnlCTop = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lblTenNhanVien = new javax.swing.JLabel();
        lblChucVu = new javax.swing.JLabel();
        pnlCCenter = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlRoot.setLayout(new java.awt.BorderLayout());

        pnlSlide.setBackground(new java.awt.Color(14, 36, 49));
        pnlSlide.setPreferredSize(new java.awt.Dimension(180, 0));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/logodelltrang-Photoroom.png"))); // NOI18N
        lblLogo.setMaximumSize(new java.awt.Dimension(130, 150));
        lblLogo.setPreferredSize(new java.awt.Dimension(120, 120));
        pnlSlide.add(lblLogo);

        btn_banhang.setBackground(new java.awt.Color(14, 36, 49));
        btn_banhang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_banhang.setForeground(new java.awt.Color(255, 255, 255));
        btn_banhang.setText("Bán Hàng");
        btn_banhang.setBorderPainted(false);
        btn_banhang.setContentAreaFilled(false);
        btn_banhang.setFocusPainted(false);
        btn_banhang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_banhang.setPreferredSize(new java.awt.Dimension(180, 70));
        btn_banhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_banhangActionPerformed(evt);
            }
        });
        pnlSlide.add(btn_banhang);

        btn_sanpham.setBackground(new java.awt.Color(14, 36, 49));
        btn_sanpham.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_sanpham.setForeground(new java.awt.Color(255, 255, 255));
        btn_sanpham.setText("Sản Phẩm");
        btn_sanpham.setBorderPainted(false);
        btn_sanpham.setContentAreaFilled(false);
        btn_sanpham.setFocusPainted(false);
        btn_sanpham.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_sanpham.setPreferredSize(new java.awt.Dimension(180, 70));
        btn_sanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sanphamActionPerformed(evt);
            }
        });
        pnlSlide.add(btn_sanpham);

        btn_nhanvien.setBackground(new java.awt.Color(14, 36, 49));
        btn_nhanvien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_nhanvien.setForeground(new java.awt.Color(255, 255, 255));
        btn_nhanvien.setText("Nhân Viên");
        btn_nhanvien.setBorderPainted(false);
        btn_nhanvien.setContentAreaFilled(false);
        btn_nhanvien.setFocusPainted(false);
        btn_nhanvien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_nhanvien.setPreferredSize(new java.awt.Dimension(180, 70));
        btn_nhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nhanvienActionPerformed(evt);
            }
        });
        pnlSlide.add(btn_nhanvien);

        btn_hoadon.setBackground(new java.awt.Color(14, 36, 49));
        btn_hoadon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_hoadon.setForeground(new java.awt.Color(255, 255, 255));
        btn_hoadon.setText("Hóa Đơn");
        btn_hoadon.setBorderPainted(false);
        btn_hoadon.setContentAreaFilled(false);
        btn_hoadon.setFocusPainted(false);
        btn_hoadon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_hoadon.setPreferredSize(new java.awt.Dimension(180, 70));
        btn_hoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hoadonActionPerformed(evt);
            }
        });
        pnlSlide.add(btn_hoadon);

        btn_khuyenmai.setBackground(new java.awt.Color(14, 36, 49));
        btn_khuyenmai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_khuyenmai.setForeground(new java.awt.Color(255, 255, 255));
        btn_khuyenmai.setText("Khuyến Mãi");
        btn_khuyenmai.setBorderPainted(false);
        btn_khuyenmai.setContentAreaFilled(false);
        btn_khuyenmai.setFocusPainted(false);
        btn_khuyenmai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_khuyenmai.setPreferredSize(new java.awt.Dimension(180, 70));
        btn_khuyenmai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_khuyenmaiActionPerformed(evt);
            }
        });
        pnlSlide.add(btn_khuyenmai);

        btn_khachhang.setBackground(new java.awt.Color(14, 36, 49));
        btn_khachhang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_khachhang.setForeground(new java.awt.Color(255, 255, 255));
        btn_khachhang.setText("Khách Hàng");
        btn_khachhang.setBorderPainted(false);
        btn_khachhang.setContentAreaFilled(false);
        btn_khachhang.setFocusPainted(false);
        btn_khachhang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_khachhang.setPreferredSize(new java.awt.Dimension(180, 70));
        btn_khachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_khachhangActionPerformed(evt);
            }
        });
        pnlSlide.add(btn_khachhang);

        btn_thongke.setBackground(new java.awt.Color(14, 36, 49));
        btn_thongke.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_thongke.setForeground(new java.awt.Color(255, 255, 255));
        btn_thongke.setText("Thống  Kê");
        btn_thongke.setBorderPainted(false);
        btn_thongke.setContentAreaFilled(false);
        btn_thongke.setFocusPainted(false);
        btn_thongke.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_thongke.setPreferredSize(new java.awt.Dimension(180, 70));
        btn_thongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thongkeActionPerformed(evt);
            }
        });
        pnlSlide.add(btn_thongke);

        btn_thoat.setBackground(new java.awt.Color(14, 36, 49));
        btn_thoat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_thoat.setForeground(new java.awt.Color(255, 255, 255));
        btn_thoat.setText("Đăng Xuất");
        btn_thoat.setBorderPainted(false);
        btn_thoat.setContentAreaFilled(false);
        btn_thoat.setFocusPainted(false);
        btn_thoat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_thoat.setPreferredSize(new java.awt.Dimension(180, 70));
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });
        pnlSlide.add(btn_thoat);

        pnlRoot.add(pnlSlide, java.awt.BorderLayout.WEST);

        pnlCenter.setBackground(new java.awt.Color(243, 244, 246));
        pnlCenter.setPreferredSize(new java.awt.Dimension(2000, 918));
        pnlCenter.setLayout(new java.awt.BorderLayout());

        pnlCTop.setBackground(new java.awt.Color(255, 183, 77));
        pnlCTop.setPreferredSize(new java.awt.Dimension(0, 130));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(1, 110));

        lblTenNhanVien.setText("Ten");

        lblChucVu.setText("Chuc vu");

        javax.swing.GroupLayout pnlCTopLayout = new javax.swing.GroupLayout(pnlCTop);
        pnlCTop.setLayout(pnlCTopLayout);
        pnlCTopLayout.setHorizontalGroup(
            pnlCTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCTopLayout.createSequentialGroup()
                .addContainerGap(12196, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addGroup(pnlCTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCTopLayout.createSequentialGroup()
                        .addComponent(lblChucVu)
                        .addGap(305, 305, 305))
                    .addGroup(pnlCTopLayout.createSequentialGroup()
                        .addComponent(lblTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))))
        );
        pnlCTopLayout.setVerticalGroup(
            pnlCTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCTopLayout.createSequentialGroup()
                .addGroup(pnlCTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addGroup(pnlCTopLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblTenNhanVien)
                        .addGap(30, 30, 30)
                        .addComponent(lblChucVu)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlCenter.add(pnlCTop, java.awt.BorderLayout.PAGE_START);

        pnlCCenter.setBackground(new java.awt.Color(255, 255, 255));
        pnlCCenter.setPreferredSize(new java.awt.Dimension(0, 100));

        javax.swing.GroupLayout pnlCCenterLayout = new javax.swing.GroupLayout(pnlCCenter);
        pnlCCenter.setLayout(pnlCCenterLayout);
        pnlCCenterLayout.setHorizontalGroup(
            pnlCCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12727, Short.MAX_VALUE)
        );
        pnlCCenterLayout.setVerticalGroup(
            pnlCCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1880, Short.MAX_VALUE)
        );

        pnlCenter.add(pnlCCenter, java.awt.BorderLayout.CENTER);

        pnlRoot.add(pnlCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlRoot, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_thongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thongkeActionPerformed
        // TODO add your handling code here:
        this.showThongKeJPanel(this);

    }//GEN-LAST:event_btn_thongkeActionPerformed

    private void btn_khachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_khachhangActionPerformed
        // TODO add your handling code here:
        this.showKhachHangJPanel(this);
    }//GEN-LAST:event_btn_khachhangActionPerformed

    private void btn_nhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nhanvienActionPerformed
        // TODO add your handling code here:
        this.showNhanVienJPanel(this);
    }//GEN-LAST:event_btn_nhanvienActionPerformed

    private void btn_khuyenmaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_khuyenmaiActionPerformed
        // TODO add your handling code here:
        this.showKhuyenMaiJPanel(this);
    }//GEN-LAST:event_btn_khuyenmaiActionPerformed

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
      int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn đăng xuất?", "Đăng xuất", JOptionPane.YES_NO_OPTION);
      if (confirm == JOptionPane.YES_OPTION) {
        this.dispose(); // Đóng cửa sổ hiện tại

        // Gọi lại form đăng nhập và đưa ra giữa màn hình
        LoginJDialog login = new LoginJDialog(null, true);
        login.setLocationRelativeTo(null); // Đưa dialog ra giữa màn hình
        login.setVisible(true);

        // Nếu đăng nhập thành công thì mở lại JFrame chính với nhân viên vừa đăng nhập
        if (login.isLoggedIn()) {
            DellStoreJFrame main = new DellStoreJFrame(login.getNvLogin());
            main.setLocationRelativeTo(null); // Đưa JFrame ra giữa màn hình
            main.setVisible(true);
        }
    }
    }//GEN-LAST:event_btn_thoatActionPerformed

    private void btn_banhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_banhangActionPerformed
        // TODO add your handling code here:
//        this.show
        this.showBanHangJPanel(this);
    }//GEN-LAST:event_btn_banhangActionPerformed

    private void btn_sanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sanphamActionPerformed
        // TODO add your handling code here:
        this.showSanPhamJPanel(this);
    }//GEN-LAST:event_btn_sanphamActionPerformed

    private void btn_hoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hoadonActionPerformed
        // TODO add your handling code here:
        this.showHoaDonJPanel(this);
    }//GEN-LAST:event_btn_hoadonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(getClass().getResource("/ICON/logodelltrang-Photoroom.png")); // ảnh trong thư mục src/images/
        Image img = icon.getImage();
        Image scaledImg = img.getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(), Image.SCALE_SMOOTH);
        lblLogo.setIcon(new ImageIcon(scaledImg));
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//       
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DellStoreJFrame(nvLogin).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_banhang;
    private javax.swing.JButton btn_hoadon;
    private javax.swing.JButton btn_khachhang;
    private javax.swing.JButton btn_khuyenmai;
    private javax.swing.JButton btn_nhanvien;
    private javax.swing.JButton btn_sanpham;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_thongke;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTenNhanVien;
    private javax.swing.JPanel pnlCCenter;
    private javax.swing.JPanel pnlCTop;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JPanel pnlSlide;
    // End of variables declaration//GEN-END:variables

    @Override
    public void init() {
        this.showHomeJPanel(this);
    }

    @Override
    public void showHomeJPanel(JFrame frame) {
        HomeJPanel panel = new HomeJPanel();
        showPanel(panel);
    }

    @Override
    public void showBanHangJPanel(JFrame frame) {
        BanHangJPanel panel = new BanHangJPanel();
        showPanel(panel);
    }

    @Override
    public void showHoaDonJPanel(JFrame frame) {
        HoaDonJPanel panel = new HoaDonJPanel();
        showPanel(panel);
    }

    @Override
    public void showNhanVienJPanel(JFrame frame) {
        NhanVienJPanel nhanVienPanel = new NhanVienJPanel();
        showPanel(nhanVienPanel);
    }

    @Override
    public void showSanPhamJPanel(JFrame frame) {
        SanPhamJPanel sanPhamJPanel = new SanPhamJPanel();
        showPanel(sanPhamJPanel);
    }
    
    @Override
    public void showKhuyenMaiJPanel(JFrame frame) {
        KhuyenMaiJPanel khuyenmaiJPanel = new KhuyenMaiJPanel();
        showPanel(khuyenmaiJPanel);
    }
    
    @Override
    public void showKhachHangJPanel(JFrame frame) {
        KhachHangJPanel JPanel = new KhachHangJPanel();
        showPanel(JPanel);
    }
    
    @Override
    public void showThongKeJPanel(JFrame frame) {
      ThongKeJPanel JPanel = new ThongKeJPanel();
        showPanel(JPanel);
    }
    public NhanVien getNvLogin() {
    return nvLogin;
}
}
