/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import java.awt.Color;
import javax.swing.JDesktopPane;

/**
 *
 * @author admin
 */
public class Trangchu_DUAN1 extends javax.swing.JFrame {

    
    
    Color  DefaultColor,ClickedColor;
    /**
     * Creates new form Trangchu_DUAN1
     */
    public Trangchu_DUAN1() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        DefaultColor = new Color(13,36,51);
        ClickedColor = new Color(240,151,57);
        
        
        
        Trang_chu.setBackground(DefaultColor);
        Ban_hang.setBackground(DefaultColor);
        San_pham.setBackground(DefaultColor);
        Hoa_don.setBackground(DefaultColor);
        Nhan_vien.setBackground(DefaultColor);
        Khach_hang.setBackground(DefaultColor);
        Thong_ke.setBackground(DefaultColor);
        Giam_gia.setBackground(DefaultColor);
        dang_suat.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Menuname = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Trang_chu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Ban_hang = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        San_pham = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Hoa_don = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Nhan_vien = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Khach_hang = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Thong_ke = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        dang_suat = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Giam_gia = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BÁN HÀNG THỜI TRANG");
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(1364, 798));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(240, 151, 47));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menuname.setBackground(new java.awt.Color(255, 255, 255));
        Menuname.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Menuname.setForeground(new java.awt.Color(255, 255, 255));
        Menuname.setText("TRANG CHỦ");
        jPanel1.add(Menuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, -1, -1));

        jPanel3.setBackground(new java.awt.Color(240, 151, 47));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/avatar.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("PH62216");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setText("Nguyễn Minh Phong ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, 220, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/logo 4.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1350, 100);

        jPanel2.setBackground(new java.awt.Color(13, 36, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Trang_chu.setBackground(new java.awt.Color(13, 36, 51));
        Trang_chu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Trang_chuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Trang_chuMousePressed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/trangchu (1).png"))); // NOI18N
        jLabel1.setText("TRANG CHỦ");

        javax.swing.GroupLayout Trang_chuLayout = new javax.swing.GroupLayout(Trang_chu);
        Trang_chu.setLayout(Trang_chuLayout);
        Trang_chuLayout.setHorizontalGroup(
            Trang_chuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Trang_chuLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        Trang_chuLayout.setVerticalGroup(
            Trang_chuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Trang_chuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        jPanel2.add(Trang_chu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 50));

        Ban_hang.setBackground(new java.awt.Color(13, 36, 51));
        Ban_hang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ban_hangMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Ban_hangMousePressed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/banhang (1).png"))); // NOI18N
        jLabel8.setText("BÁN HÀNG");

        javax.swing.GroupLayout Ban_hangLayout = new javax.swing.GroupLayout(Ban_hang);
        Ban_hang.setLayout(Ban_hangLayout);
        Ban_hangLayout.setHorizontalGroup(
            Ban_hangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ban_hangLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel8)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        Ban_hangLayout.setVerticalGroup(
            Ban_hangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Ban_hangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(Ban_hang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 210, -1));

        San_pham.setBackground(new java.awt.Color(13, 36, 51));
        San_pham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                San_phamMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                San_phamMousePressed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/sanpham.png"))); // NOI18N
        jLabel9.setText("SẢN PHẨM");

        javax.swing.GroupLayout San_phamLayout = new javax.swing.GroupLayout(San_pham);
        San_pham.setLayout(San_phamLayout);
        San_phamLayout.setHorizontalGroup(
            San_phamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(San_phamLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        San_phamLayout.setVerticalGroup(
            San_phamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(San_phamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(San_pham, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 210, -1));

        Hoa_don.setBackground(new java.awt.Color(13, 36, 51));
        Hoa_don.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Hoa_donMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Hoa_donMousePressed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/donhang (1).png"))); // NOI18N
        jLabel10.setText("HÓA ĐƠN");

        javax.swing.GroupLayout Hoa_donLayout = new javax.swing.GroupLayout(Hoa_don);
        Hoa_don.setLayout(Hoa_donLayout);
        Hoa_donLayout.setHorizontalGroup(
            Hoa_donLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Hoa_donLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel10)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        Hoa_donLayout.setVerticalGroup(
            Hoa_donLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(Hoa_don, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        Nhan_vien.setBackground(new java.awt.Color(13, 36, 51));
        Nhan_vien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Nhan_vienMousePressed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/nhanvien (1).png"))); // NOI18N
        jLabel11.setText("NHÂN VIÊN");

        javax.swing.GroupLayout Nhan_vienLayout = new javax.swing.GroupLayout(Nhan_vien);
        Nhan_vien.setLayout(Nhan_vienLayout);
        Nhan_vienLayout.setHorizontalGroup(
            Nhan_vienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Nhan_vienLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        Nhan_vienLayout.setVerticalGroup(
            Nhan_vienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Nhan_vienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        jPanel2.add(Nhan_vien, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 210, -1));

        Khach_hang.setBackground(new java.awt.Color(13, 36, 51));
        Khach_hang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Khach_hangMousePressed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/khachhang (1).png"))); // NOI18N
        jLabel12.setText("KHÁCH HÀNG");

        javax.swing.GroupLayout Khach_hangLayout = new javax.swing.GroupLayout(Khach_hang);
        Khach_hang.setLayout(Khach_hangLayout);
        Khach_hangLayout.setHorizontalGroup(
            Khach_hangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Khach_hangLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel12)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        Khach_hangLayout.setVerticalGroup(
            Khach_hangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(Khach_hang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 210, -1));

        Thong_ke.setBackground(new java.awt.Color(13, 36, 51));
        Thong_ke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Thong_keMousePressed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/thongke (2).png"))); // NOI18N
        jLabel13.setText("THỐNG KÊ");

        javax.swing.GroupLayout Thong_keLayout = new javax.swing.GroupLayout(Thong_ke);
        Thong_ke.setLayout(Thong_keLayout);
        Thong_keLayout.setHorizontalGroup(
            Thong_keLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Thong_keLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        Thong_keLayout.setVerticalGroup(
            Thong_keLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Thong_keLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        jPanel2.add(Thong_ke, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        dang_suat.setBackground(new java.awt.Color(13, 36, 51));
        dang_suat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dang_suatMousePressed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/logout.png"))); // NOI18N
        jLabel14.setText("ĐĂNG XUẤT");

        javax.swing.GroupLayout dang_suatLayout = new javax.swing.GroupLayout(dang_suat);
        dang_suat.setLayout(dang_suatLayout);
        dang_suatLayout.setHorizontalGroup(
            dang_suatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dang_suatLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel14)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        dang_suatLayout.setVerticalGroup(
            dang_suatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(dang_suat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, -1, 50));

        Giam_gia.setBackground(new java.awt.Color(13, 36, 51));
        Giam_gia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Giam_giaMousePressed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/phieugiamgia.png"))); // NOI18N
        jLabel15.setText("GIẢM GIÁ");

        javax.swing.GroupLayout Giam_giaLayout = new javax.swing.GroupLayout(Giam_gia);
        Giam_gia.setLayout(Giam_giaLayout);
        Giam_giaLayout.setHorizontalGroup(
            Giam_giaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Giam_giaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        Giam_giaLayout.setVerticalGroup(
            Giam_giaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Giam_giaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(Giam_gia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 210, -1));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 100, 230, 670);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(230, 100, 1120, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Trang_chuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Trang_chuMousePressed
        // TODO add your handling code here:
          Trang_chu.setBackground(ClickedColor);
        Ban_hang.setBackground(DefaultColor);
        San_pham.setBackground(DefaultColor);
        Hoa_don.setBackground(DefaultColor);
        Nhan_vien.setBackground(DefaultColor);
        Khach_hang.setBackground(DefaultColor);
        Thong_ke.setBackground(DefaultColor);
        Giam_gia.setBackground(DefaultColor);
        dang_suat.setBackground(DefaultColor);
        
        Menuname.setText("TRANG CHỦ");
        
    }//GEN-LAST:event_Trang_chuMousePressed

    private void Ban_hangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ban_hangMousePressed
        // TODO add your handling code here:
          Trang_chu.setBackground(DefaultColor);
        Ban_hang.setBackground(ClickedColor);
        San_pham.setBackground(DefaultColor);
        Hoa_don.setBackground(DefaultColor);
        Nhan_vien.setBackground(DefaultColor);
        Khach_hang.setBackground(DefaultColor);
        Thong_ke.setBackground(DefaultColor);
        Giam_gia.setBackground(DefaultColor);
        dang_suat.setBackground(DefaultColor);
        Menuname.setText("BÁN HÀNG");
    }//GEN-LAST:event_Ban_hangMousePressed

    private void San_phamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_San_phamMousePressed
        // TODO add your handling code here:
          Trang_chu.setBackground(DefaultColor);
        Ban_hang.setBackground(DefaultColor);
        San_pham.setBackground(ClickedColor);
        Hoa_don.setBackground(DefaultColor);
        Nhan_vien.setBackground(DefaultColor);
        Khach_hang.setBackground(DefaultColor);
        Thong_ke.setBackground(DefaultColor);
        Giam_gia.setBackground(DefaultColor);
        dang_suat.setBackground(DefaultColor);
        Menuname.setText("SẢN PHẨM");
        
    }//GEN-LAST:event_San_phamMousePressed

    private void Hoa_donMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Hoa_donMousePressed
        // TODO add your handling code here:
          Trang_chu.setBackground(DefaultColor);
        Ban_hang.setBackground(DefaultColor);
        San_pham.setBackground(DefaultColor);
        Hoa_don.setBackground(ClickedColor);
        Nhan_vien.setBackground(DefaultColor);
        Khach_hang.setBackground(DefaultColor);
        Thong_ke.setBackground(DefaultColor);
        Giam_gia.setBackground(DefaultColor);
        dang_suat.setBackground(DefaultColor);
        Menuname.setText("HÓA ĐƠN");
    }//GEN-LAST:event_Hoa_donMousePressed

    private void Nhan_vienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Nhan_vienMousePressed
        // TODO add your handling code here:
          Trang_chu.setBackground(DefaultColor);
        Ban_hang.setBackground(DefaultColor);
        San_pham.setBackground(DefaultColor);
        Hoa_don.setBackground(DefaultColor);
        Nhan_vien.setBackground(ClickedColor);
        Khach_hang.setBackground(DefaultColor);
        Thong_ke.setBackground(DefaultColor);
        Giam_gia.setBackground(DefaultColor);
        dang_suat.setBackground(DefaultColor);
        Menuname.setText("NHÂN VIÊN");
    }//GEN-LAST:event_Nhan_vienMousePressed

    private void Khach_hangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Khach_hangMousePressed
        // TODO add your handling code here:
          Trang_chu.setBackground(DefaultColor);
        Ban_hang.setBackground(DefaultColor);
        San_pham.setBackground(DefaultColor);
        Hoa_don.setBackground(DefaultColor);
        Nhan_vien.setBackground(DefaultColor);
        Khach_hang.setBackground(ClickedColor);
        Thong_ke.setBackground(DefaultColor);
        Giam_gia.setBackground(DefaultColor);
        dang_suat.setBackground(DefaultColor);
        
        Menuname.setText("KHÁCH HÀNG");
    }//GEN-LAST:event_Khach_hangMousePressed

    private void Thong_keMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Thong_keMousePressed
        // TODO add your handling code here:
          Trang_chu.setBackground(DefaultColor);
        Ban_hang.setBackground(DefaultColor);
        San_pham.setBackground(DefaultColor);
        Hoa_don.setBackground(DefaultColor);
        Nhan_vien.setBackground(DefaultColor);
        Khach_hang.setBackground(DefaultColor);
        Giam_gia.setBackground(DefaultColor);
        dang_suat.setBackground(DefaultColor);
        Thong_ke.setBackground(ClickedColor);
        
        
        Menuname.setText("THÔNG KÊ");
    }//GEN-LAST:event_Thong_keMousePressed

    private void Trang_chuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Trang_chuMouseClicked
        // TODO add your handling code here:
        TRANG_CHU trangchu = new TRANG_CHU();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(trangchu).setVisible(true);
    }//GEN-LAST:event_Trang_chuMouseClicked

    private void dang_suatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dang_suatMousePressed
        // TODO add your handling code here:
         Trang_chu.setBackground(DefaultColor);
        Ban_hang.setBackground(DefaultColor);
        San_pham.setBackground(DefaultColor);
        Hoa_don.setBackground(DefaultColor);
        Nhan_vien.setBackground(DefaultColor);
        Khach_hang.setBackground(DefaultColor);
        Thong_ke.setBackground(DefaultColor);
        dang_suat.setBackground(ClickedColor);
        Giam_gia.setBackground(DefaultColor);
        
        Menuname.setText("ĐĂNG XUẤT");
    }//GEN-LAST:event_dang_suatMousePressed

    private void Ban_hangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ban_hangMouseClicked
        // TODO add your handling code here:
        BAN_HANG banhang = new BAN_HANG();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(banhang).setVisible(true);
    }//GEN-LAST:event_Ban_hangMouseClicked

    private void Hoa_donMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Hoa_donMouseClicked
        // TODO add your handling code here:
        HOA_DON hoadon = new HOA_DON();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(hoadon).setVisible(true);
    }//GEN-LAST:event_Hoa_donMouseClicked

    private void Giam_giaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Giam_giaMousePressed
        // TODO add your handling code here:
         
        Trang_chu.setBackground(DefaultColor);
        Ban_hang.setBackground(DefaultColor);
        San_pham.setBackground(DefaultColor);
        Hoa_don.setBackground(DefaultColor);
        Nhan_vien.setBackground(DefaultColor);
        Khach_hang.setBackground(DefaultColor);
        Thong_ke.setBackground(DefaultColor);
        dang_suat.setBackground(DefaultColor);
        Giam_gia.setBackground(ClickedColor);
        
        
        Menuname.setText("GIẢM GIÁ");
    }//GEN-LAST:event_Giam_giaMousePressed

    private void San_phamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_San_phamMouseClicked
        // TODO add your handling code here:
        SAN_PHAM sanpham = new SAN_PHAM();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(sanpham).setVisible(true);
    }//GEN-LAST:event_San_phamMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trangchu_DUAN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trangchu_DUAN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trangchu_DUAN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trangchu_DUAN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trangchu_DUAN1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Ban_hang;
    private javax.swing.JPanel Giam_gia;
    private javax.swing.JPanel Hoa_don;
    private javax.swing.JPanel Khach_hang;
    private javax.swing.JLabel Menuname;
    private javax.swing.JPanel Nhan_vien;
    private javax.swing.JPanel San_pham;
    private javax.swing.JPanel Thong_ke;
    private javax.swing.JPanel Trang_chu;
    private javax.swing.JPanel dang_suat;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
